### ISSUE TITLE
Ability to contribute to SpringTest?

### ISSUE THREAD

**Issue by checketts** [petrbalat/kd4smt#7]
I would like to take the DSL as it currently is, and try to contribute it directly into SpringTest. This project has an MIT license, so the licensing isn't a problem. I just wanted to keep you in the loop. 

Is that acceptable?

**Comment by petrbalat** [comment]
it's acceptable of course.

**Comment by checketts** [comment]
PR opened at https://github.com/spring-projects/spring-framework/pull/1951 I've added you as a collaborator on my repo if you wanted to contribute to the PR

**Comment by checketts** [comment]
We can close this now since it is merged into the Spring Framework. I also added some test conversions that take the existing tests and convert them to the built in Spring DSL. See [DslControllerConvertedToBuiltInDslTest](https://github.com/petrbalat/kd4smt/blob/master/src/test/kotlin/cz/petrbalat/spring/mvc/test/dsl/controller/DslControllerConvertedToBuiltInDslTest.kt). To support it I added a few extension functions (see [MiniDSL](https://github.com/petrbalat/kd4smt/blob/master/src/test/kotlin/cz/petrbalat/spring/mvc/test/dsl/MiniDSL.kt) to demonstrate to others if there was an approach they missed and wanted to add back to the Spring Boot DSL.
